Create VPC
SaintClair33/DevOpsProject pull request #3
Opened 2022-07-26 02:14 UTC by SaintClair33

Pull request for Terraform creation of VPC

2022-07-26 03:22 UTC, vladimirmukhin requested changes
Please run `terraform fmt` - it will automatically make some code style adjustments. After that commit changes to the same branch

2022-07-26 03:24 UTC, vladimirmukhin requested changes

2022-07-26 03:24 UTC, vladimirmukhin commented on vpc/main.tf
> +}
```suggestion
  }
}
```

2022-07-26 03:24 UTC, vladimirmukhin commented on vpc/main.tf
> +}
Please end each file with a newline

2022-07-26 03:24 UTC, vladimirmukhin commented on vpc/providers.tf
> +
Please have only one newline at the end of a file

2022-07-27 23:51 UTC, SaintClair33 reviewed
Vlad did I get all of the changes? I thought I submitted all of the changes you recommended, can you confirm?

2022-07-27 23:55 UTC, vladimirmukhin approved these changes

2022-07-27 23:56 UTC, merged